//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhacoxsInjector {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpString() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhacoxsInjector.HelpString", typeof(HelpString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aspect ratio.
        /// </summary>
        internal static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the aspect ratio you prefer to view the game on both TV and GamePad..
        /// </summary>
        internal static string AspectRatioDescription {
            get {
                return ResourceManager.GetString("AspectRatioDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base.
        /// </summary>
        internal static string Base {
            get {
                return ResourceManager.GetString("Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base checked.
        /// </summary>
        internal static string BaseChecked {
            get {
                return ResourceManager.GetString("BaseChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base was loaded correctly..
        /// </summary>
        internal static string BaseCheckedDescription {
            get {
                return ResourceManager.GetString("BaseCheckedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base game currently loaded..
        /// </summary>
        internal static string BaseDescription {
            get {
                return ResourceManager.GetString("BaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base error.
        /// </summary>
        internal static string BaseError {
            get {
                return ResourceManager.GetString("BaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base is invalid..
        /// </summary>
        internal static string BaseInvalid {
            get {
                return ResourceManager.GetString("BaseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning! &quot;resources\unpack\CDecrypt.exe&quot; not found! CDecrypt allows you to unpack (decrypt) Wii U VC games to use as base..
        /// </summary>
        internal static string CDecryptWarning {
            get {
                return ResourceManager.GetString("CDecryptWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose N64 configuration file.
        /// </summary>
        internal static string ChooseN64ConfigFile {
            get {
                return ResourceManager.GetString("ChooseN64ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the &quot;.ini&quot; file that contains configuration data for the game you want to inject..
        /// </summary>
        internal static string ChooseN64ConfigFileDescription {
            get {
                return ResourceManager.GetString("ChooseN64ConfigFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose ROM.
        /// </summary>
        internal static string ChooseROM {
            get {
                return ResourceManager.GetString("ChooseROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the ROM file of the game you want to inject..
        /// </summary>
        internal static string ChooseROMDescription {
            get {
                return ResourceManager.GetString("ChooseROMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning! &quot;resources\pack\CNUSPACKER.exe&quot; not found! CNUSPacker allows you to pack (encrypt) the result for WUP Installer..
        /// </summary>
        internal static string CNUSPackerWarning {
            get {
                return ResourceManager.GetString("CNUSPackerWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dark filter.
        /// </summary>
        internal static string DarkFilter {
            get {
                return ResourceManager.GetString("DarkFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable or disable the dark filter in the game display..
        /// </summary>
        internal static string DarkFilterDescription {
            get {
                return ResourceManager.GetString("DarkFilterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit N64 configuration file.
        /// </summary>
        internal static string EditN64ConfigFile {
            get {
                return ResourceManager.GetString("EditN64ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create or modify the &quot;.ini&quot; configuration file for the N64 game you want to inject. Unfortunately there is not much information about what each option does. (Recommended for advanced users only)..
        /// </summary>
        internal static string EditN64ConfigFileDescription {
            get {
                return ResourceManager.GetString("EditN64ConfigFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To enable the buttons in the Injecting section you have to choose a ROM, put a name and load a base..
        /// </summary>
        internal static string EnableInjecting {
            get {
                return ResourceManager.GetString("EnableInjecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the folder where the injection result will be saved..
        /// </summary>
        internal static string FolderResultSelect {
            get {
                return ResourceManager.GetString("FolderResultSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GamePad.
        /// </summary>
        internal static string GamePad {
            get {
                return ResourceManager.GetString("GamePad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change the image that will appear on the GamePad when the game starts..
        /// </summary>
        internal static string GamePadDescription {
            get {
                return ResourceManager.GetString("GamePadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GamePad preview.
        /// </summary>
        internal static string GamePadPreview {
            get {
                return ResourceManager.GetString("GamePadPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview the image that will appear in the GamePad when the game starts..
        /// </summary>
        internal static string GamePadPreviewDescription {
            get {
                return ResourceManager.GetString("GamePadPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base did not load. Use one of the GBA games released for the Wii U VC..
        /// </summary>
        internal static string GBABaseErrorDescription {
            get {
                return ResourceManager.GetString("GBABaseErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Wii U GBA Virtual Console game..
        /// </summary>
        internal static string GBABaseSelect {
            get {
                return ResourceManager.GetString("GBABaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string HelpBox {
            get {
                return ResourceManager.GetString("HelpBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable or disable this help box..
        /// </summary>
        internal static string HelpDescription {
            get {
                return ResourceManager.GetString("HelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change the icon that will appear in the console menu..
        /// </summary>
        internal static string IconDescription {
            get {
                return ResourceManager.GetString("IconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icon preview.
        /// </summary>
        internal static string IconPreview {
            get {
                return ResourceManager.GetString("IconPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview the image that will appear in the console menu..
        /// </summary>
        internal static string IconPreviewDescription {
            get {
                return ResourceManager.GetString("IconPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Injecting.
        /// </summary>
        internal static string Injecting {
            get {
                return ResourceManager.GetString("Injecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The injection failed..
        /// </summary>
        internal static string InjectionFailed {
            get {
                return ResourceManager.GetString("InjectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The injection was completed successfully!.
        /// </summary>
        internal static string InjectionSuccessfully {
            get {
                return ResourceManager.GetString("InjectionSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning! If you use this option, you will receive a failed injection. Enter the Wii U common key (see Settings section)..
        /// </summary>
        internal static string InjectionWarningWiiUCK {
            get {
                return ResourceManager.GetString("InjectionWarningWiiUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep image for GamePad.
        /// </summary>
        internal static string KeepImageGamePad {
            get {
                return ResourceManager.GetString("KeepImageGamePad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By selecting this option, the image for GamePad will remain unchanged. Useful if you just want to edit some virtual console settings without altering anything else..
        /// </summary>
        internal static string KeepImageGamePadDescription {
            get {
                return ResourceManager.GetString("KeepImageGamePadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep image for TV.
        /// </summary>
        internal static string KeepImageTV {
            get {
                return ResourceManager.GetString("KeepImageTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By selecting this option, the image for TV will remain unchanged. Useful if you just want to edit some virtual console settings without altering anything else..
        /// </summary>
        internal static string KeepImageTVDescription {
            get {
                return ResourceManager.GetString("KeepImageTVDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keep menu icon.
        /// </summary>
        internal static string KeepMenuIcon {
            get {
                return ResourceManager.GetString("KeepMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a By selecting this option, the menu icon will remain unchanged. Useful if you just want to edit some virtual console settings without altering anything else..
        /// </summary>
        internal static string KeepMenuIconDescription {
            get {
                return ResourceManager.GetString("KeepMenuIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load base.
        /// </summary>
        internal static string LoadBase {
            get {
                return ResourceManager.GetString("LoadBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A base game is not a ROM, it is a Wii U Virtual Console game. The base game is essential, since this will obtain the necessary files to run the ROM on the Wii U. Although not all ROMs are compatible with the Wii U Virtual Console..
        /// </summary>
        internal static string LoadBaseDescription {
            get {
                return ResourceManager.GetString("LoadBaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning! You will not be able to load a packed base (WUP format). Enter the Wii U common key (see Settings section)..
        /// </summary>
        internal static string LoadBaseWarningWiiUCK {
            get {
                return ResourceManager.GetString("LoadBaseWarningWiiUCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Once an injection is made, it shows the contents of the program log file..
        /// </summary>
        internal static string LogDescription {
            get {
                return ResourceManager.GetString("LogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Long name.
        /// </summary>
        internal static string LongName {
            get {
                return ResourceManager.GetString("LongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name of two lines that will appear in the console menu and in the template images (see the Images section)..
        /// </summary>
        internal static string LongNameBoxesDescription {
            get {
                return ResourceManager.GetString("LongNameBoxesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable or disable the long name..
        /// </summary>
        internal static string LongNameDescription {
            get {
                return ResourceManager.GetString("LongNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mode select.
        /// </summary>
        internal static string ModeSelect {
            get {
                return ResourceManager.GetString("ModeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select the application mode. &quot;Auto&quot; allows you to select any compatible ROM and adapts the application automatically. Or select the specific console to have the template images and limit the selection of ROMs according to the console..
        /// </summary>
        internal static string ModeSelectDescription {
            get {
                return ResourceManager.GetString("ModeSelectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are about to change the application mode, having previously selected a ROM. The change will make you have to select a ROM again..
        /// </summary>
        internal static string ModeSelectWarning {
            get {
                return ResourceManager.GetString("ModeSelectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base did not load. Use one of the N64 games released for the Wii U VC..
        /// </summary>
        internal static string N64BaseErrorDescription {
            get {
                return ResourceManager.GetString("N64BaseErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Wii U N64 Virtual Console game..
        /// </summary>
        internal static string N64BaseSelect {
            get {
                return ResourceManager.GetString("N64BaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N64 configuration file.
        /// </summary>
        internal static string N64ConfigFile {
            get {
                return ResourceManager.GetString("N64ConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;.Ini&quot; file that contains configuration data for the game you want to inject. Not all games have their corresponding configuration file. You can try leaving it empty..
        /// </summary>
        internal static string N64ConfigFileDescription {
            get {
                return ResourceManager.GetString("N64ConfigFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The N64 configuration file is invalid. An empty file will be injected..
        /// </summary>
        internal static string N64ConfigFileInvalid {
            get {
                return ResourceManager.GetString("N64ConfigFileInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base did not load. Use one of the NDS games released for the Wii U VC..
        /// </summary>
        internal static string NDSBaseErrorDescription {
            get {
                return ResourceManager.GetString("NDSBaseErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Wii U NDS Virtual Console game..
        /// </summary>
        internal static string NDSBaseSelect {
            get {
                return ResourceManager.GetString("NDSBaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NDS icon background.
        /// </summary>
        internal static string NDSIconBackground {
            get {
                return ResourceManager.GetString("NDSIconBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some icons do not look good with a black background; you can change it to the color you prefer..
        /// </summary>
        internal static string NDSIconBackgroundDescription {
            get {
                return ResourceManager.GetString("NDSIconBackgroundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NDS icon preview.
        /// </summary>
        internal static string NDSIconPreview {
            get {
                return ResourceManager.GetString("NDSIconPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Displays the icon that was extracted from the NDS game ROM..
        /// </summary>
        internal static string NDSIconPreviewDescription {
            get {
                return ResourceManager.GetString("NDSIconPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base did not load. Use one of the NES games released for the Wii U VC..
        /// </summary>
        internal static string NESBaseErrorDescription {
            get {
                return ResourceManager.GetString("NESBaseErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Wii U NES Virtual Console game..
        /// </summary>
        internal static string NESBaseSelect {
            get {
                return ResourceManager.GetString("NESBaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Not pack.
        /// </summary>
        internal static string NotPack {
            get {
                return ResourceManager.GetString("NotPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perform the injection and copy the result in the path you select. For loadiine..
        /// </summary>
        internal static string NotPackDescription {
            get {
                return ResourceManager.GetString("NotPackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pack.
        /// </summary>
        internal static string Pack {
            get {
                return ResourceManager.GetString("Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perform the injection and pack the result in the path you select. For WUP Installer..
        /// </summary>
        internal static string PackDescription {
            get {
                return ResourceManager.GetString("PackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indicates the maximum number of players that supports the game you want to inject..
        /// </summary>
        internal static string PlayersDescription {
            get {
                return ResourceManager.GetString("PlayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Product code.
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Internal value of the ROM file that identifies the game..
        /// </summary>
        internal static string ProductCodeDescription {
            get {
                return ResourceManager.GetString("ProductCodeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Release date.
        /// </summary>
        internal static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable or disable the display of the game release date in the template images..
        /// </summary>
        internal static string ReleaseDateDescription {
            get {
                return ResourceManager.GetString("ReleaseDateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ROM.
        /// </summary>
        internal static string ROM {
            get {
                return ResourceManager.GetString("ROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The ROM file of the game you want to inject..
        /// </summary>
        internal static string ROMDescription {
            get {
                return ResourceManager.GetString("ROMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ROM size.
        /// </summary>
        internal static string ROMSize {
            get {
                return ResourceManager.GetString("ROMSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use this information to determine if you can inject the ROM into the loaded base. At the moment you can only inject ROMs of the same or smaller size to which the base ROM size indicates..
        /// </summary>
        internal static string ROMSizeDescription {
            get {
                return ResourceManager.GetString("ROMSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Short name.
        /// </summary>
        internal static string ShortName {
            get {
                return ResourceManager.GetString("ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If the long name is not enabled, the short name will be used for all menus in the console and in the template images (see the Images section)..
        /// </summary>
        internal static string ShortNameDescription {
            get {
                return ResourceManager.GetString("ShortNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show name.
        /// </summary>
        internal static string ShowName {
            get {
                return ResourceManager.GetString("ShowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable or disable the display of the name of the game in the template images..
        /// </summary>
        internal static string ShowNameDescription {
            get {
                return ResourceManager.GetString("ShowNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Players.
        /// </summary>
        internal static string ShowPlayers {
            get {
                return ResourceManager.GetString("ShowPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of game players that will appear in the template images..
        /// </summary>
        internal static string ShowPlayersDescription {
            get {
                return ResourceManager.GetString("ShowPlayersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The base did not load. Use one of the SNES games released for the Wii U VC..
        /// </summary>
        internal static string SNESBaseErrorDescription {
            get {
                return ResourceManager.GetString("SNESBaseErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a Wii U SNES Virtual Console game..
        /// </summary>
        internal static string SNESBaseSelect {
            get {
                return ResourceManager.GetString("SNESBaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound volume.
        /// </summary>
        internal static string SoundVolume {
            get {
                return ResourceManager.GetString("SoundVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modify the volume of the game audio. Official games do not exceed 140. (This option is only available in Super Famicom or SNES base juices with &quot;Extended footer: True&quot;)..
        /// </summary>
        internal static string SoundVolumeDescription {
            get {
                return ResourceManager.GetString("SoundVolumeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Speed.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the frame rate that corresponds to the region of the game you want to inject. 60 FPS for NTSC games (USA/JPN) or 50 FPS for PAL games (EUR)..
        /// </summary>
        internal static string SpeedDescription {
            get {
                return ResourceManager.GetString("SpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title ID.
        /// </summary>
        internal static string TitleID {
            get {
                return ResourceManager.GetString("TitleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value that identifies the game within the console..
        /// </summary>
        internal static string TitleIDDescription {
            get {
                return ResourceManager.GetString("TitleIDDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title screen.
        /// </summary>
        internal static string TitleScreen {
            get {
                return ResourceManager.GetString("TitleScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an image to represent the game in the template images..
        /// </summary>
        internal static string TitleScreenDescription {
            get {
                return ResourceManager.GetString("TitleScreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Translation.
        /// </summary>
        internal static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scroll the game display area. If you move it too much, you can leave the screen..
        /// </summary>
        internal static string TranslationDescription {
            get {
                return ResourceManager.GetString("TranslationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TV.
        /// </summary>
        internal static string TV {
            get {
                return ResourceManager.GetString("TV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change the image that will appear on the TV when the game starts..
        /// </summary>
        internal static string TVDescription {
            get {
                return ResourceManager.GetString("TVDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TV preview.
        /// </summary>
        internal static string TVPreview {
            get {
                return ResourceManager.GetString("TVPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview the image that will appear on TV when the game starts..
        /// </summary>
        internal static string TVPreviewDescription {
            get {
                return ResourceManager.GetString("TVPreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use NDS icon.
        /// </summary>
        internal static string UseNDSIcon {
            get {
                return ResourceManager.GetString("UseNDSIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instead of a title screen image you can use the NDS game icon..
        /// </summary>
        internal static string UseNDSIconDescription {
            get {
                return ResourceManager.GetString("UseNDSIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Virtual Console target.
        /// </summary>
        internal static string VirtualConsoleTarget {
            get {
                return ResourceManager.GetString("VirtualConsoleTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Widescreen.
        /// </summary>
        internal static string Widescreen {
            get {
                return ResourceManager.GetString("Widescreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable or disable the wide screen in the game display. This modifies the aspect ratio of the game from 4:3 to 16:9..
        /// </summary>
        internal static string WidescreenDescription {
            get {
                return ResourceManager.GetString("WidescreenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wii U Common Key.
        /// </summary>
        internal static string WiiUCommonKey {
            get {
                return ResourceManager.GetString("WiiUCommonKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put the Wii U Common Key here, if the key is correct this text box will disable and a green check mark will appear next to it..
        /// </summary>
        internal static string WiiUCommonKeyBoxDescription {
            get {
                return ResourceManager.GetString("WiiUCommonKeyBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wii U common key checked.
        /// </summary>
        internal static string WiiUCommonKeyChecked {
            get {
                return ResourceManager.GetString("WiiUCommonKeyChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The common key was loaded correctly..
        /// </summary>
        internal static string WiiUCommonKeyCheckedDescription {
            get {
                return ResourceManager.GetString("WiiUCommonKeyCheckedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Common key to pack or unpack Wii U games..
        /// </summary>
        internal static string WiiUCommonKeyDescription {
            get {
                return ResourceManager.GetString("WiiUCommonKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wii U common key error.
        /// </summary>
        internal static string WiiUCommonKeyError {
            get {
                return ResourceManager.GetString("WiiUCommonKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The common key was not found. Without it you will not be able to decrypt the Wii U games to use as a base or encrypt the result for WUP Installer. (Search it on Google)..
        /// </summary>
        internal static string WiiUCommonKeyErrorDescription {
            get {
                return ResourceManager.GetString("WiiUCommonKeyErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enlarge or reduce the viewing area of the game. If you expand it a lot you can leave the screen..
        /// </summary>
        internal static string ZoomDescription {
            get {
                return ResourceManager.GetString("ZoomDescription", resourceCulture);
            }
        }
    }
}
